## 1. Project Overview

The Customer Feedback Intelligence System is designed to analyze
customer reviews and convert customer feedback into meaningful
business insights using Data Science, Natural Language Processing,
and Machine Learning techniques.

The system will analyze customer ratings and textual feedback to
understand customer sentiment, complaints, appreciated features,
and important customer-feedback aspects.

## 2. Problem Statement

A large number of customer reviews are difficult to analyze
manually. Important information about customer satisfaction,
complaints, product quality, and customer expectations may be
hidden inside unstructured review text.

Therefore, this project aims to analyze customer feedback
systematically using Data Science, NLP, and Machine Learning
techniques.

In [3]:
import pandas as pd
import numpy as np
a = r"C:\archive\Dataset.csv"
df = pd.read_csv(a, encoding="latin1")
print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

C:\Users\Admin\AppData\Local\Temp\ipykernel_9796\3745282079.py:4: DtypeWarning: Columns (0: Rate) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(a, encoding="latin1")

In [4]:
df

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Nice product,A Good cooler by Crompton. The height of the c...
...,...,...,...,...,...
363256,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Terrific,Thanks
363257,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Terrific,Good
363258,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Just wow!,Super
363259,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,4.0,Worth the money,Good
363260,,NaN,NaN,NaN,NaN

## 3. Dataset Understanding

The dataset contains customer feedback information. It will be
examined to understand its size, columns, data types, records,
statistical information, missing values, and duplicate records.

In [8]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])
print("Dataset Shape:", df.shape)

Number of Rows: 363261
Number of Columns: 5
Dataset Shape: (363261, 5)

In [9]:
print("Column Names:")
print(df.columns.tolist())

Column Names:
['Product_name', 'Price', 'Rate', 'Review', 'Summary']

In [10]:
df.head()

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Nice product,A Good cooler by Crompton. The height of the c...

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 363261 entries, 0 to 363260
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Product_name  363246 non-null  str
 1   Price         363245 non-null  str
 2   Rate          363245 non-null  object
 3   Review        363239 non-null  str
 4   Summary       361239 non-null  str
dtypes: object(1), str(4)
memory usage: 13.9+ MB

In [17]:
df.tail()

,Product_name,Price,Rate,Review,Summary
363256,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Terrific,Thanks
363257,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Terrific,Good
363258,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Just wow!,Super
363259,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,4.0,Worth the money,Good
363260,,NaN,NaN,NaN,NaN

In [18]:
df.describe(include="all")

,Product_name,Price,Rate,Review,Summary
count,363246,363245,363245,363239,361239
unique,1175,709,14,3841,165850
top,Bumtum Baby Pull-Up Diaper Pants Combo Pack - ...,"??4,499",5,Wonderful,Good
freq,9937,12633,146763,18567,25001

In [21]:

print("Missing Values:")
display(df.isnull().sum())

print("Duplicate Rows:", df.duplicated().sum())

Missing Values:

Product_name      15
Price             16
Rate              16
Review            22
Summary         2022
dtype: int64

Duplicate Rows: 52466

## 4. Business Objective

The main objective of the project is to convert customer feedback
into useful business insights.

The analysis will focus on customer sentiment, common complaints,
appreciated features, important aspects of customer feedback, and
differences in feedback across products or categories.

## 5. Project Scope

The project covers data understanding, data cleaning, exploratory
data analysis, NLP preprocessing, feature extraction, sentiment
classification, model evaluation, aspect analysis, business
insights, and dashboard development.