# Customer Feedback Intelligence System

## Day 2 — Data Cleaning

**Project Type:** Data Science / Machine Learning / NLP  

**Domain:** Customer Analytics, NLP, Machine Learning

## 1. Objective

The objective of this stage is to clean and prepare the customer
feedback dataset for Exploratory Data Analysis, NLP preprocessing,
and Machine Learning.

The data cleaning process includes checking missing values,
duplicate records, data types, invalid values, and preparing
important columns for further analysis.

## 2. Import Required Libraries

In [3]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

## 3. Load Dataset

The original customer feedback dataset is loaded for data cleaning.

In [5]:
a = r"C:\archive\Dataset.csv"

df = pd.read_csv(a, encoding="latin1")

print("Dataset loaded successfully!")
print("Dataset Shape:", df.shape)

Dataset loaded successfully!
Dataset Shape: (363261, 5)

C:\Users\Admin\AppData\Local\Temp\ipykernel_2640\870967750.py:3: DtypeWarning: Columns (0: Rate) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(a, encoding="latin1")

In [6]:
df

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Nice product,A Good cooler by Crompton. The height of the c...
...,...,...,...,...,...
363256,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Terrific,Thanks
363257,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Terrific,Good
363258,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Just wow!,Super
363259,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,4.0,Worth the money,Good
363260,,NaN,NaN,NaN,NaN

## 4. Initial Dataset Inspection

The first few records are displayed to understand the structure
and content of the dataset before performing cleaning operations.

In [7]:
df.head()

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Nice product,A Good cooler by Crompton. The height of the c...

## 5. Check Dataset Information

The dataset information is examined to understand column names,
data types, and the overall structure of the dataset.

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 363261 entries, 0 to 363260
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Product_name  363246 non-null  str
 1   Price         363245 non-null  str
 2   Rate          363245 non-null  object
 3   Review        363239 non-null  str
 4   Summary       361239 non-null  str
dtypes: object(1), str(4)
memory usage: 13.9+ MB

## 6. Check Missing Values

Missing values are checked in all columns before performing
any data cleaning operations.

In [9]:
print("Missing Values:")
display(df.isnull().sum())

Missing Values:

Product_name      15
Price             16
Rate              16
Review            22
Summary         2022
dtype: int64

## 6.1 Missing Value Percentage

The percentage of missing values is calculated for each column to
understand the extent of missing data in the dataset.

In [10]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print("Missing Value Percentage:")
display(missing_percentage)

Missing Value Percentage:

Product_name    0.004129
Price           0.004405
Rate            0.004405
Review          0.006056
Summary         0.556625
dtype: float64

## 7. Check Duplicate Records

Duplicate records are checked to identify repeated rows in the
dataset before further cleaning.

In [11]:
duplicate_count = df.duplicated().sum()

print("Number of Duplicate Rows:", duplicate_count)

Number of Duplicate Rows: 52466

## 8. Remove Duplicate Records

Duplicate records are removed to avoid repeated data from affecting
the results of further analysis and machine learning tasks.

In [12]:
rows_before = len(df)

df = df.drop_duplicates()

rows_after = len(df)

print("Rows Before Removing Duplicates:", rows_before)
print("Rows After Removing Duplicates:", rows_after)
print("Duplicate Rows Removed:", rows_before - rows_after)

Rows Before Removing Duplicates: 363261
Rows After Removing Duplicates: 310795
Duplicate Rows Removed: 52466

## 9. Price Column Cleaning

The Price column contains currency symbols and unwanted characters.
These characters are removed and the column is converted into a
numerical format for further analysis.

In [13]:


df["Price"] = (
    df["Price"]
    .astype(str)
    .str.replace(r"[^\d.]", "", regex=True)
)

df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

print("Price Data Type After Cleaning:", df["Price"].dtype)

print("\nSample Price Values:")
for price in df["Price"].head(10):
    print(f"₹ {price:,.1f}")

Price Data Type After Cleaning: float64

Sample Price Values:
₹ 10,499.0
₹ 10,499.0
₹ 10,499.0
₹ 10,499.0
₹ 10,499.0
₹ 10,499.0
₹ 10,499.0
₹ 10,499.0
₹ 10,499.0
₹ 10,499.0

## 10. Rate Column Cleaning

The Rate column is converted into a numerical format so that
rating-based analysis and visualization can be performed.

In [14]:


df["Rate"] = pd.to_numeric(df["Rate"], errors="coerce")

print("Rate Data Type After Cleaning:", df["Rate"].dtype)

print("\nUnique Rating Values:")
print(df["Rate"].value_counts().sort_index())

Rate Data Type After Cleaning: float64

Unique Rating Values:
Rate
1.0     37960
2.0     12326
3.0     28233
4.0     60944
5.0    171326
Name: count, dtype: int64

## 11. Handle Missing Values

Missing values are handled based on the type and importance of
each column.

Missing product names are replaced with "Unknown Product".
Missing Price values are replaced with the median Price.
Rows with missing Rate values are removed because Rating is an
important variable for sentiment and rating-based analysis.

Missing Review and Summary values are replaced with empty strings
to make the text data suitable for NLP preprocessing.

In [15]:

df["Product_name"] = df["Product_name"].fillna("Unknown Product")


df["Price"] = df["Price"].fillna(df["Price"].median())


rows_before_rate = len(df)
df = df.dropna(subset=["Rate"])
rows_after_rate = len(df)


df["Review"] = df["Review"].fillna("")
df["Summary"] = df["Summary"].fillna("")

print("Missing values handled successfully!")
print("Rows removed due to missing Rate:", rows_before_rate - rows_after_rate)

Missing values handled successfully!
Rows removed due to missing Rate: 6

## 12. Final Missing Value Verification

Missing values are checked again after the cleaning process to
confirm that the dataset is properly prepared for further analysis.

In [16]:
print("Final Missing Values:")
display(df.isnull().sum())

Final Missing Values:

Product_name    0
Price           0
Rate            0
Review          0
Summary         0
dtype: int64

## 13. Final Dataset Verification

The cleaned dataset is verified by checking its shape, column names,
data types, and sample records before saving the final dataset.

In [17]:
print("Final Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nFirst 5 Records:")
display(df.head())

Final Dataset Shape: (310789, 5)

Column Names:
['Product_name', 'Price', 'Rate', 'Review', 'Summary']

Data Types:
Product_name        str
Price           float64
Rate            float64
Review              str
Summary             str
dtype: object

First 5 Records:

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,5.0,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,4.0,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,5.0,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,5.0,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,4.0,Nice product,A Good cooler by Crompton. The height of the c...

## 14. Product Name Text Cleaning

The Product_name column is cleaned by removing unwanted encoding
characters while preserving the actual product name.

In [18]:


df["Product_name"] = (
    df["Product_name"]
    .astype(str)
    .str.replace(r"[?]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

print("Product Name cleaned successfully!")

print("\nSample Product Names:")
display(df["Product_name"].head())

Product Name cleaned successfully!

Sample Product Names:

0    Crompton 75 L Desert Air Cooler(White, Teal, A...
1    Crompton 75 L Desert Air Cooler(White, Teal, A...
2    Crompton 75 L Desert Air Cooler(White, Teal, A...
3    Crompton 75 L Desert Air Cooler(White, Teal, A...
4    Crompton 75 L Desert Air Cooler(White, Teal, A...
Name: Product_name, dtype: str

## 15. Save Cleaned Dataset

The cleaned customer feedback dataset is saved as a new CSV file
for use in Exploratory Data Analysis, Visualization, NLP
preprocessing, and Machine Learning.

In [19]:
cleaned_file_path = r"C:\archive\Customer_Feedback_Cleaned.csv"

df.to_csv(
    cleaned_file_path,
    index=False,
    encoding="utf-8"
)

print("Cleaned dataset saved successfully!")
print("File:", cleaned_file_path)

Cleaned dataset saved successfully!
File: C:\archive\Customer_Feedback_Cleaned.csv

## 16. Result

The customer feedback dataset was successfully cleaned and prepared
for further analysis.

Duplicate records were removed, missing values were handled,
the Price and Rate columns were converted into suitable numerical
formats, and unwanted encoding characters in Product_name were
cleaned.

The cleaned dataset was successfully saved and is ready for
Exploratory Data Analysis, Visualization, NLP preprocessing,
and Machine Learning.

## 17. Learning

Through this data cleaning stage, I learned how to prepare
real-world customer feedback data for further analysis.

I learned how to identify and handle missing values, remove
duplicate records, clean numerical columns, process text data,
and save the cleaned dataset for future Data Science and
Machine Learning tasks.