# Customer Feedback Intelligence System

## Day 5 — NLP Preprocessing

**Project Type:** Data Science / Machine Learning / NLP  

**Domain:** Customer Analytics, NLP, Machine Learning

## 1. Objective

The objective of this task is to preprocess customer feedback text
for Natural Language Processing (NLP).

In this task, the `Review` and `Summary` columns will be processed
using text cleaning, tokenization, stopword removal, stemming,
and lemmatization.

The processed text will be used in the next stages for feature
engineering and sentiment analysis.

In [2]:
import pandas as pd
import re 
import nltk

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
cleaned_file_path = r"C:\archive\Customer_Feedback_Cleaned.csv"

df = pd.read_csv(cleaned_file_path, encoding="utf-8")

print("Cleaned dataset loaded successfully!")
print("Dataset Shape:", df.shape)
print("Columns:", df.columns.tolist())

Cleaned dataset loaded successfully!
Dataset Shape: (310789, 5)
Columns: ['Product_name', 'Price', 'Rate', 'Review', 'Summary']

## 2. Inspect Review and Summary Text

The `Review` and `Summary` columns contain customer feedback text.

Before applying NLP preprocessing, sample records are inspected to
understand the structure and content of the text data.

In [7]:
print("Sample Customer Reviews:")
display(df["Review"].head(10))

print("\nSample Customer Summaries:")
display(df["Summary"].head(10))

Sample Customer Reviews:

0                         simply awesome
1    worth money desert cooler live name
2                      worth every penny
3                               fabulous
4                           nice product
5                                  super
6                      terrific purchase
7                         classy product
8                        perfect product
9                       cooler ac cooler
Name: Review, dtype: str

Sample Customer Summaries:

0    it's really worth every single penny. it works...
1    I bought Crompton Ozone 75 Desert Air Cooler i...
2    GREAT packaging by seller. As this was the mos...
3    Delivery was delayed by two days except this e...
4    A Good cooler by Crompton. The height of the c...
5    Can't go wrong with Crompton Brand, In Punjab ...
6    A great cooler in great price. Compact and Gre...
7    Its an awesome product and I am not making any...
8    Air throw is very good.????????Low noise and b...
9    Its been 6 days that i am using this cooler we...
Name: Summary, dtype: str

## 3. Text Cleaning

Text cleaning is performed to remove unnecessary characters and
standardize the customer feedback text.

The `Review` and `Summary` columns are converted to lowercase,
special characters and numbers are removed, and extra spaces are
eliminated.

This step prepares the text for further NLP processing.

In [8]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


df["Cleaned_Review"] = df["Review"].apply(clean_text)
df["Cleaned_Summary"] = df["Summary"].apply(clean_text)

print("Text cleaning completed successfully!")

display(
    df[["Review", "Cleaned_Review", "Summary", "Cleaned_Summary"]].head(10)
)

Text cleaning completed successfully!

,Review,Cleaned_Review,Summary,Cleaned_Summary
0,simply awesome,simply awesome,it's really worth every single penny. it works...,its really worth every single penny it works l...
1,worth money desert cooler live name,worth money desert cooler live name,I bought Crompton Ozone 75 Desert Air Cooler i...,i bought crompton ozone desert air cooler in t...
2,worth every penny,worth every penny,GREAT packaging by seller. As this was the mos...,great packaging by seller as this was the most...
3,fabulous,fabulous,Delivery was delayed by two days except this e...,delivery was delayed by two days except this e...
4,nice product,nice product,A Good cooler by Crompton. The height of the c...,a good cooler by crompton the height of the co...
5,super,super,"Can't go wrong with Crompton Brand, In Punjab ...",cant go wrong with crompton brand in punjab th...
6,terrific purchase,terrific purchase,A great cooler in great price. Compact and Gre...,a great cooler in great price compact and grea...
7,classy product,classy product,Its an awesome product and I am not making any...,its an awesome product and i am not making any...
8,perfect product,perfect product,Air throw is very good.????????Low noise and b...,air throw is very goodlow noise and best cooli...
9,cooler ac cooler,cooler ac cooler,Its been 6 days that i am using this cooler we...,its been days that i am using this cooler we h...

## 4. Tokenization

Tokenization is the process of splitting text into individual words
or tokens.

In this step, the cleaned `Review` and `Summary` text will be
converted into lists of individual words.

Tokenization is an important step because NLP models work with
individual words or tokens during further text processing.

In [9]:
from nltk.tokenize import word_tokenize

nltk.download("punkt")
nltk.download("punkt_tab")

df["Review_Tokens"] = df["Cleaned_Review"].apply(word_tokenize)
df["Summary_Tokens"] = df["Cleaned_Summary"].apply(word_tokenize)

print("Tokenization completed successfully!")

display(
    df[
        [
            "Cleaned_Review",
            "Review_Tokens",
            "Cleaned_Summary",
            "Summary_Tokens"
        ]
    ].head(10)
)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Tokenization completed successfully!

,Cleaned_Review,Review_Tokens,Cleaned_Summary,Summary_Tokens
0,simply awesome,"[simply, awesome]",its really worth every single penny it works l...,"[its, really, worth, every, single, penny, it,..."
1,worth money desert cooler live name,"[worth, money, desert, cooler, live, name]",i bought crompton ozone desert air cooler in t...,"[i, bought, crompton, ozone, desert, air, cool..."
2,worth every penny,"[worth, every, penny]",great packaging by seller as this was the most...,"[great, packaging, by, seller, as, this, was, ..."
3,fabulous,[fabulous],delivery was delayed by two days except this e...,"[delivery, was, delayed, by, two, days, except..."
4,nice product,"[nice, product]",a good cooler by crompton the height of the co...,"[a, good, cooler, by, crompton, the, height, o..."
5,super,[super],cant go wrong with crompton brand in punjab th...,"[cant, go, wrong, with, crompton, brand, in, p..."
6,terrific purchase,"[terrific, purchase]",a great cooler in great price compact and grea...,"[a, great, cooler, in, great, price, compact, ..."
7,classy product,"[classy, product]",its an awesome product and i am not making any...,"[its, an, awesome, product, and, i, am, not, m..."
8,perfect product,"[perfect, product]",air throw is very goodlow noise and best cooli...,"[air, throw, is, very, goodlow, noise, and, be..."
9,cooler ac cooler,"[cooler, ac, cooler]",its been days that i am using this cooler we h...,"[its, been, days, that, i, am, using, this, co..."

## 5. Stopword Removal

Stopwords are common words such as `the`, `is`, `and`, `of`, and `to`
that usually provide limited meaning for text analysis.

In this step, stopwords will be removed from the tokenized `Review`
and `Summary` text.

This helps reduce unnecessary words and keeps the more meaningful
terms for further NLP processing.

In [10]:
from nltk.corpus import stopwords

nltk.download("stopwords")

stop_words = set(stopwords.words("english"))

df["Filtered_Review_Tokens"] = df["Review_Tokens"].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

df["Filtered_Summary_Tokens"] = df["Summary_Tokens"].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

print("Stopword removal completed successfully!")

display(
    df[
        [
            "Review_Tokens",
            "Filtered_Review_Tokens",
            "Summary_Tokens",
            "Filtered_Summary_Tokens"
        ]
    ].head(10)
)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Stopword removal completed successfully!

,Review_Tokens,Filtered_Review_Tokens,Summary_Tokens,Filtered_Summary_Tokens
0,"[simply, awesome]","[simply, awesome]","[its, really, worth, every, single, penny, it,...","[really, worth, every, single, penny, works, l..."
1,"[worth, money, desert, cooler, live, name]","[worth, money, desert, cooler, live, name]","[i, bought, crompton, ozone, desert, air, cool...","[bought, crompton, ozone, desert, air, cooler,..."
2,"[worth, every, penny]","[worth, every, penny]","[great, packaging, by, seller, as, this, was, ...","[great, packaging, seller, important, point, t..."
3,[fabulous],[fabulous],"[delivery, was, delayed, by, two, days, except...","[delivery, delayed, two, days, except, everyth..."
4,"[nice, product]","[nice, product]","[a, good, cooler, by, crompton, the, height, o...","[good, cooler, crompton, height, cooler, ft, i..."
5,[super],[super],"[cant, go, wrong, with, crompton, brand, in, p...","[cant, go, wrong, crompton, brand, punjab, exc..."
6,"[terrific, purchase]","[terrific, purchase]","[a, great, cooler, in, great, price, compact, ...","[great, cooler, great, price, compact, great, ..."
7,"[classy, product]","[classy, product]","[its, an, awesome, product, and, i, am, not, m...","[awesome, product, making, fake, comments, bou..."
8,"[perfect, product]","[perfect, product]","[air, throw, is, very, goodlow, noise, and, be...","[air, throw, goodlow, noise, best, cooling, me..."
9,"[cooler, ac, cooler]","[cooler, ac, cooler]","[its, been, days, that, i, am, using, this, co...","[days, using, cooler, room, buying, cooler, lo..."

## 6. Stemming

Stemming is the process of reducing words to their root or base form
by removing word endings.

In this step, the Porter Stemmer will be applied to the filtered
tokens from both the `Review` and `Summary` columns.

Stemming helps reduce different forms of a word to a common form,
which can reduce the number of unique terms during text analysis.

In [ ]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

df["Stemmed_Review_Tokens"] = df["Filtered_Review_Tokens"].apply(
    lambda tokens: [stemmer.stem(word) for word in tokens]
)

df["Stemmed_Summary_Tokens"] = df["Filtered_Summary_Tokens"].apply(
    lambda tokens: [stemmer.stem(word) for word in tokens]
)

print("Stemming completed successfully!")

display(
    df[
        [
            "Filtered_Review_Tokens",
            "Stemmed_Review_Tokens",
            "Filtered_Summary_Tokens",
            "Stemmed_Summary_Tokens"
        ]
    ].head(10)
)

## 7. Lemmatization

Lemmatization is the process of converting words into their meaningful
base or dictionary form.

Unlike stemming, lemmatization produces valid words by considering
the actual language structure.

In this step, lemmatization will be applied to the filtered tokens
from both the `Review` and `Summary` columns.

In [12]:
from nltk.stem import WordNetLemmatizer

nltk.download("wordnet")
nltk.download("omw-1.4")

lemmatizer = WordNetLemmatizer()

df["Lemmatized_Review_Tokens"] = df["Filtered_Review_Tokens"].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

df["Lemmatized_Summary_Tokens"] = df["Filtered_Summary_Tokens"].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

print("Lemmatization completed successfully!")

display(
    df[
        [
            "Filtered_Review_Tokens",
            "Lemmatized_Review_Tokens",
            "Filtered_Summary_Tokens",
            "Lemmatized_Summary_Tokens"
        ]
    ].head(10)
)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Lemmatization completed successfully!

,Filtered_Review_Tokens,Lemmatized_Review_Tokens,Filtered_Summary_Tokens,Lemmatized_Summary_Tokens
0,"[simply, awesome]","[simply, awesome]","[really, worth, every, single, penny, works, l...","[really, worth, every, single, penny, work, li..."
1,"[worth, money, desert, cooler, live, name]","[worth, money, desert, cooler, live, name]","[bought, crompton, ozone, desert, air, cooler,...","[bought, crompton, ozone, desert, air, cooler,..."
2,"[worth, every, penny]","[worth, every, penny]","[great, packaging, seller, important, point, t...","[great, packaging, seller, important, point, t..."
3,[fabulous],[fabulous],"[delivery, delayed, two, days, except, everyth...","[delivery, delayed, two, day, except, everythi..."
4,"[nice, product]","[nice, product]","[good, cooler, crompton, height, cooler, ft, i...","[good, cooler, crompton, height, cooler, ft, i..."
5,[super],[super],"[cant, go, wrong, crompton, brand, punjab, exc...","[cant, go, wrong, crompton, brand, punjab, exc..."
6,"[terrific, purchase]","[terrific, purchase]","[great, cooler, great, price, compact, great, ...","[great, cooler, great, price, compact, great, ..."
7,"[classy, product]","[classy, product]","[awesome, product, making, fake, comments, bou...","[awesome, product, making, fake, comment, boug..."
8,"[perfect, product]","[perfect, product]","[air, throw, goodlow, noise, best, cooling, me...","[air, throw, goodlow, noise, best, cooling, me..."
9,"[cooler, ac, cooler]","[cooler, ac, cooler]","[days, using, cooler, room, buying, cooler, lo...","[day, using, cooler, room, buying, cooler, lov..."

## 8. Create Final Processed Text

The lemmatized tokens are converted back into text format to create
the final processed text.

The processed `Review` and `Summary` texts will be used in the next
stage for feature engineering and TF-IDF feature extraction.

In [13]:
df["Processed_Review"] = df["Lemmatized_Review_Tokens"].apply(
    lambda tokens: " ".join(tokens)
)

df["Processed_Summary"] = df["Lemmatized_Summary_Tokens"].apply(
    lambda tokens: " ".join(tokens)
)

print("Final processed text created successfully!")

display(
    df[
        [
            "Review",
            "Processed_Review",
            "Summary",
            "Processed_Summary"
        ]
    ].head(10)
)

Final processed text created successfully!

,Review,Processed_Review,Summary,Processed_Summary
0,simply awesome,simply awesome,it's really worth every single penny. it works...,really worth every single penny work like one ...
1,worth money desert cooler live name,worth money desert cooler live name,I bought Crompton Ozone 75 Desert Air Cooler i...,bought crompton ozone desert air cooler month ...
2,worth every penny,worth every penny,GREAT packaging by seller. As this was the mos...,great packaging seller important point transpo...
3,fabulous,fabulous,Delivery was delayed by two days except this e...,delivery delayed two day except everything qui...
4,nice product,nice product,A Good cooler by Crompton. The height of the c...,good cooler crompton height cooler ft inch col...
5,super,super,"Can't go wrong with Crompton Brand, In Punjab ...",cant go wrong crompton brand punjab excellent ...
6,terrific purchase,terrific purchase,A great cooler in great price. Compact and Gre...,great cooler great price compact great design ...
7,classy product,classy product,Its an awesome product and I am not making any...,awesome product making fake comment bought tri...
8,perfect product,perfect product,Air throw is very good.????????Low noise and b...,air throw goodlow noise best cooling medium sp...
9,cooler ac cooler,cooler ac cooler,Its been 6 days that i am using this cooler we...,day using cooler room buying cooler love stron...

## 9. Save the Cleaned Dataset

The NLP preprocessing steps have been completed for both the `Review`
and `Summary` columns.

The intermediate NLP columns are temporary and are not required in
the final cleaned dataset. Therefore, only the original five dataset
columns are retained and saved.

The original `Dataset.csv` remains unchanged.

In [15]:
final_columns = [
    "Product_name",
    "Price",
    "Rate",
    "Processed_Review",
    "Processed_Summary"
]

df_final = df[final_columns].copy()

df_final = df_final.rename(
    columns={
        "Processed_Review": "Review",
        "Processed_Summary": "Summary"
    }
)

df_final.to_csv(
    cleaned_file_path,
    index=False,
    encoding="utf-8"
)

print("NLP processed dataset saved successfully!")
print("Final Shape:", df_final.shape)
print("Final Columns:", df_final.columns.tolist())

NLP processed dataset saved successfully!
Final Shape: (310789, 5)
Final Columns: ['Product_name', 'Price', 'Rate', 'Review', 'Summary']

## 10. Verify the Final Dataset

The final cleaned dataset is verified to ensure that the required
columns are present and the processed `Review` and `Summary` text
has been saved correctly.

Only the five required dataset columns are retained in the final file.

In [16]:

df_check = pd.read_csv(cleaned_file_path, encoding="utf-8")

print("Final dataset loaded successfully!")
print("Shape:", df_check.shape)
print("Columns:", df_check.columns.tolist())

print("\nSample Processed Reviews:")
display(df_check["Review"].head(5))

print("\nSample Processed Summaries:")
display(df_check["Summary"].head(5))

Final dataset loaded successfully!
Shape: (310789, 5)
Columns: ['Product_name', 'Price', 'Rate', 'Review', 'Summary']

Sample Processed Reviews:

0                         simply awesome
1    worth money desert cooler live name
2                      worth every penny
3                               fabulous
4                           nice product
Name: Review, dtype: str

Sample Processed Summaries:

0    really worth every single penny work like one ...
1    bought crompton ozone desert air cooler month ...
2    great packaging seller important point transpo...
3    delivery delayed two day except everything qui...
4    good cooler crompton height cooler ft inch col...
Name: Summary, dtype: str

## 11. Conclusion

The NLP preprocessing stage was successfully completed for both
customer `Review` and `Summary` text.

The text was cleaned, tokenized, filtered by removing stopwords,
stemmed, and lemmatized. The final processed text was saved in the
cleaned dataset for use in the upcoming feature engineering and
sentiment analysis stages.