# Customer Feedback Intelligence System

## Day 6 — Feature Engineering

**Project Type:** Data Science / Machine Learning / NLP 

**Domain:** Customer Analytics, NLP, Machine Learning

## 1. Objective 

The Objective of this task is to transform the preprocessed customer feedback text into numerical features that can be used by customer learning models.

In this task, sentiment labels will be created, TF-IDF feature extraction will be applied using unigrams and bigrams, and the dataset will be divided into traning and testing sets.

In [2]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

print("Libraries imported successfully!")

Libraries imported successfully!

## 2. Load Cleaned Dataset

The cleaned customer feedback dataset prepared during the NLP
preprocessing stage is loaded for feature engineering.

The dataset contains preprocessed `Review` and `Summary` text,
which will be used for sentiment labeling and TF-IDF feature
extraction.

In [3]:
cleaned_file_path = r"C:\archive\Customer_Feedback_Cleaned.csv"

df = pd.read_csv(cleaned_file_path, encoding="utf-8")

print("Cleaned dataset Loaded Successfully!")
print("Dataset Shape:", df.shape)
print("Columns:", df.columns.tolist())

Cleaned dataset Loaded Successfully!
Dataset Shape: (310789, 5)
Columns: ['Product_name', 'Price', 'Rate', 'Review', 'Summary']

## 3. Create Sentiment Labels

The customer rating is used to create sentiment labels for sentiment
analysis.

Ratings of 4 and 5 are considered **Positive**, rating 3 is considered
**Neutral**, and ratings of 1 and 2 are considered **Negative**.

These sentiment labels will be used as the target variable for the
machine learning models in the next stages.

In [4]:
def create_sentiment(rating):
    if rating >=4:
        return "Positive"
    elif rating == 3:
        return "Neutral"
    else:
        return "Negative"

df["Sentiment"] = df["Rate"].apply(create_sentiment)

print("Sentiment labels created successfully!")

display(df[["Rate", "Sentiment"]].head(10))

Sentiment labels created successfully!

   Rate Sentiment
0     5  Positive
1     4  Positive
2     5  Positive
3     5  Positive
4     4  Positive
5     5  Positive
6     5  Positive
7     5  Positive
8     5  Positive
9     5  Positive

In [5]:
df["Combined_Text"] = (
    df["Review"].fillna("") + " " + df["Summary"].fillna("")
)

print("Review and Summary combined successfully!")

display(
    df[
        ["Review", "Summary", "Combined_Text"]
        ].head(10)
)

Review and Summary combined successfully!

,Review,Summary,Combined_Text
0,simply awesome,really worth every single penny work like one ...,simply awesome really worth every single penny...
1,worth money desert cooler live name,bought crompton ozone desert air cooler month ...,worth money desert cooler live name bought cro...
2,worth every penny,great packaging seller important point transpo...,worth every penny great packaging seller impor...
3,fabulous,delivery delayed two day except everything qui...,fabulous delivery delayed two day except every...
4,nice product,good cooler crompton height cooler ft inch col...,nice product good cooler crompton height coole...
5,super,cant go wrong crompton brand punjab excellent ...,super cant go wrong crompton brand punjab exce...
6,terrific purchase,great cooler great price compact great design ...,terrific purchase great cooler great price com...
7,classy product,awesome product making fake comment bought tri...,classy product awesome product making fake com...
8,perfect product,air throw goodlow noise best cooling medium sp...,perfect product air throw goodlow noise best c...
9,cooler ac cooler,day using cooler room buying cooler love stron...,cooler ac cooler day using cooler room buying ...

## 5. Train-Test Split

The combined customer feedback text and sentiment labels are divided
into training and testing datasets.

The training data will be used to build the machine learning model,
while the testing data will be used to evaluate the model on unseen
customer feedback.

An 80:20 split is used, with 80% of the data for training and 20%
for testing.

In [7]:
X = df["Combined_Text"]
y = df["Sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Train-Test split completed successfully!")

print("Traning samples:", len(X_train))
print("Testing samples:", len(X_test))

Train-Test split completed successfully!
Traning samples: 248631
Testing samples: 62158

## 6. TF-IDF Feature Extraction

TF-IDF (Term Frequency-Inverse Document Frequency) is used to convert
customer feedback text into numerical features.

It assigns higher importance to words that are frequent in a particular
document but less common across the complete dataset.

Both unigrams (single words) and bigrams (two-word combinations) are
included to capture meaningful word patterns from customer feedback.

In [9]:


tfidf_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    max_features=5000,
    min_df=2
)


X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)


X_test_tfidf = tfidf_vectorizer.transform(X_test)

print("TF-IDF feature extraction completed successfully!")

print("Training TF-IDF Shape:", X_train_tfidf.shape)
print("Testing TF-IDF Shape:", X_test_tfidf.shape)

TF-IDF feature extraction completed successfully!
Training TF-IDF Shape: (248631, 5000)
Testing TF-IDF Shape: (62158, 5000)

## 7. Inspect TF-IDF Features

The generated TF-IDF features are inspected to verify the feature
names and the dimensions of the training and testing feature matrices.

This confirms that the customer feedback text has been successfully
converted into numerical features for machine learning.

In [10]:
feature_names = tfidf_vectorizer.get_feature_names_out()

print("Numbers of TF-IDF Features:", len(feature_names))

print("\nFirst 20 TF-IDF Features:")
print(feature_names[:20])

print("\nTraning TF-IDF Shape:", X_train_tfidf.shape)
print("Testing TF-IDF Shape:", X_test_tfidf.shape)

Numbers of TF-IDF Features: 5000

First 20 TF-IDF Features:
['able' 'absolute' 'absolute rubbish' 'absolutely' 'absolutely fine'
 'absorb' 'absorbing' 'absorption' 'ac' 'accept' 'acceptable' 'accepted'
 'access' 'accessory' 'according' 'according price' 'accurate' 'across'
 'act' 'action']

Traning TF-IDF Shape: (248631, 5000)
Testing TF-IDF Shape: (62158, 5000)

## 8. Sentiment Label Distribution

The distribution of sentiment labels is examined to understand the
number of Positive, Neutral, and Negative customer feedback records.

This helps identify whether the sentiment classes are reasonably
balanced before building the machine learning models.

In [12]:
sentiment_counts = df["Sentiment"].value_counts()

print("Sentiment Label Distribution:")
print(sentiment_counts)

print("\nTraning Sentiment Distribution:")
print(y_train.value_counts())

print("\nTesting Sentiment Distribution:")
print(y_test.value_counts())

Sentiment Label Distribution:
Sentiment
Positive    232270
Negative     50286
Neutral      28233
Name: count, dtype: int64

Traning Sentiment Distribution:
Sentiment
Positive    185816
Negative     40229
Neutral      22586
Name: count, dtype: int64

Testing Sentiment Distribution:
Sentiment
Positive    46454
Negative    10057
Neutral      5647
Name: count, dtype: int64

## 9. Feature Engineering

The feature engineering stage was successfully completed.

Sentiment labels were created using customer ratings, and the
preprocessed Review and Summary text was combined into a single text
feature. The text data was converted into numerical features using
TF-IDF with unigrams and bigrams.

The dataset was divided into training and testing sets, and the
resulting features were verified for machine learning model
development.

The engineered features are now ready for the model building stage.

In [13]:
print("Day 6 - Feature Engineering completed successfully!")

print("\nTraining TF-IDF Shape:", X_train_tfidf.shape)
print("Testing TF-IDF Shape:", X_test_tfidf.shape)

print("\nSentiment Classes:")
print(y.unique())

print("\nNumber of TF-IDF Features:", len(feature_names))

Day 6 - Feature Engineering completed successfully!

Training TF-IDF Shape: (248631, 5000)
Testing TF-IDF Shape: (62158, 5000)

Sentiment Classes:
<StringArray>
['Positive', 'Neutral', 'Negative']
Length: 3, dtype: str

Number of TF-IDF Features: 5000